version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: push-notifications

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - type: bind
        source: ./scripts/wait-for-it.sh
        target: /wait-for-it.sh
    entrypoint:
      - /bin/bash
      - /wait-for-it.sh
      - mongo:27017
      - --
      - /docker-entrypoint.sh

  web:
    build: .
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./scripts/wait-for-it.sh
        target: /wait-for-it.sh
    environment:
      MONGODB_CONNSTRING: mongodb://root:example@mongo:27017/push-notifications?authSource=admin
    entrypoint:
      - /bin/bash
      - /wait-for-it.sh
      - mongo:27017
      - --
      - ./scripts/docker-entrypoint.sh